import {requireMember} from '@/lib/auth';
import {can} from '@/lib/domain';
import {marriageInput} from '@/lib/marriage-domain';
import {eligibility,requireEligible,visibleMarriage,marriagePublic} from '@/lib/marriage';
import {AppError,failure,guardOrigin,json} from '@/lib/security';
import {audit,db,id,insert,list,notice,one,rate,record,update} from '@/lib/store';
import {z} from 'zod';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const {member:m}=await requireMember();const view=new URL(req.url).searchParams.get('view')||'mine';await rate('marriage-read:'+m.id,100,300);const mine=(await list(m.tenant,'marriage')).find(r=>r.owner===m.id);
 if(view==='mine')return json({eligibility:await eligibility(m),profile:mine?{id:mine.id,status:mine.status,profile:mine.profile,reason:mine.reason}:null,requests:(await list(m.tenant,'marriage-interest')).filter(r=>r.owner===m.id||r.targetOwner===m.id&&r.status!=='Reçue').map(r=>({id:r.id,alias:r.owner===m.id?r.targetAlias:r.sourceAlias,direction:r.owner===m.id?'out':'in',status:r.status}))});
 if(view==='admin'){if(!can(m,'admin'))throw new AppError(403,'Administration uniquement.');return json({profiles:(await list(m.tenant,'marriage')).map(r=>({id:r.id,status:r.status,profile:r.profile,reason:r.reason,photo:'/api/marriage/photo?id='+r.id})),requests:(await list(m.tenant,'marriage-interest')).map(r=>({id:r.id,sourceAlias:r.sourceAlias,targetAlias:r.targetAlias,status:r.status,reason:r.reason}))})}
 if(view==='directory'){await requireEligible(m);const q=new URL(req.url).searchParams;const out=[];for(const r of await list(m.tenant,'marriage')){if(r.owner===m.id||!await visibleMarriage(r))continue;const p=marriagePublic(r);if(['gender','age','situation','salat','wish'].some(k=>q.get(k)&&q.get(k)!=='all'&&(p as any)[k]!==q.get(k)))continue;if(q.get('nationality')&&!p.nationality.toLocaleLowerCase('fr').includes(q.get('nationality')!.trim().toLocaleLowerCase('fr')))continue;if(q.get('mobility')&&q.get('mobility')!=='all'&&!p.mobility.includes(q.get('mobility')))continue;if(q.get('children')==='none'&&p.children!=='Aucun')continue;out.push(p)}const page=Math.max(0,Math.min(1000,Number(q.get('page'))||0));return json({items:out.slice(page*12,page*12+12),total:out.length,page})}throw new AppError(404,'Rubrique inconnue.')
}catch(e){return failure(e)}}
export async function POST(req:Request){try{guardOrigin(req);if(Number(req.headers.get('content-length')||0)>20000)throw new AppError(413,'Requête trop volumineuse.');const raw=await req.text();if(raw.length>20000)throw new AppError(413,'Requête trop volumineuse.');const b=JSON.parse(raw);const {member:m}=await requireMember();await rate('marriage-write:'+m.id,20,3600);const mine=(await list(m.tenant,'marriage')).find(r=>r.owner===m.id);
 if(b.action==='withdraw'){if(!mine)throw new AppError(404,'Dossier introuvable.');await update(m,mine,{...JSON.parse(mine.data),status:'Retiré',profile:{...mine.profile,consentDisplay:false,consentPhoto:false}},'mariage_consentement_retire');return json({message:'Votre profil et votre photo ne sont plus visibles.'})}
 if(b.action==='submit'){await requireEligible(m);const profile=marriageInput.parse(b.profile);const photo=await record(m.tenant,profile.photo);if(!photo||photo.kind!=='file'||photo.purpose!=='marriage_photo'||photo.owner!==m.id)throw new AppError(400,'Ajoutez votre photo personnelle dans ce formulaire.');const data={profile,status:'En attente',reason:'',consentVersion:'2026-09-24',consentedAt:new Date().toISOString()};if(mine)await update(m,mine,data,'mariage_dossier_modifie');else await db().batch([insert(m.tenant,'marriage',m.id,data,'marriage:'+m.tenant+':'+m.id),audit(m,'mariage_dossier_soumis',m.id)]);return json({message:photo.scan==='clean'?'Dossier transmis à l’administration.':'Dossier reçu. La photo attend son analyse de sécurité avant validation.'})}
 if(b.action==='review'){if(!can(m,'admin'))throw new AppError(403,'Administration uniquement.');const r=await record(m.tenant,String(b.id));if(!r||r.kind!=='marriage')throw new AppError(404,'Dossier introuvable.');if(r.owner===m.id)throw new AppError(403,'Un autre administrateur doit examiner votre propre dossier.');const accept=z.boolean().parse(b.accept);const reason=z.string().trim().min(3).max(600).parse(b.reason);if(accept){if(!r.profile.consentDisplay||!r.profile.consentPhoto)throw new AppError(409,'Le consentement a été retiré.');const owner=await one('SELECT * FROM members WHERE tenant=? AND id=?',m.tenant,r.owner);await requireEligible(owner);const photo=await record(m.tenant,r.profile.photo);if(photo?.scan!=='clean')throw new AppError(409,'L’analyse de sécurité de la photo doit être terminée.')}await update(m,r,{...JSON.parse(r.data),status:accept?'Approuvé':'Rejeté',reason},'mariage_dossier_examine');await notice({id:r.owner,tenant:m.tenant} as any,'Service Mariage',accept?'Votre profil a été validé.':reason).run();return json({message:'Décision enregistrée.'})}
 if(b.action==='interest'){await requireEligible(m);if(!mine||!await visibleMarriage(mine))throw new AppError(403,'Faites valider votre propre profil avant une demande.');const target=await record(m.tenant,String(b.target));if(!target||target.kind!=='marriage'||target.owner===m.id||!await visibleMarriage(target))throw new AppError(404,'Profil indisponible.');const key='marriage-interest:'+m.tenant+':'+m.id+':'+target.id;if(await record(m.tenant,key))throw new AppError(409,'Une demande existe déjà pour ce profil.');await db().batch([insert(m.tenant,'marriage-interest',m.id,{target:target.id,targetOwner:target.owner,sourceAlias:mine.profile.alias,targetAlias:target.profile.alias,status:'Reçue',reason:z.string().trim().max(300).parse(b.reason||'')},key),audit(m,'mariage_interet_transmis',key)]);return json({message:'Votre demande est transmise aux administrateurs. Aucune coordonnée n’a été partagée.'})}
 if(b.action==='request_review'){if(!can(m,'admin'))throw new AppError(403,'Administration uniquement.');const r=await record(m.tenant,String(b.id));if(!r||r.kind!=='marriage-interest')throw new AppError(404,'Demande introuvable.');if(b.status!=='Clôturée'){const source=(await list(m.tenant,'marriage')).find(x=>x.owner===r.owner);const target=await record(m.tenant,r.target);if(!source||!target||!await visibleMarriage(source)||!await visibleMarriage(target))throw new AppError(409,'Un dossier est retiré ou n’est plus éligible.');}const status=z.enum(['Consentement demandé','Accompagnement en cours','Clôturée']).parse(b.status);if(status==='Accompagnement en cours'&&r.status!=='Accord donné')throw new AppError(409,'L’accord du destinataire doit d’abord être recueilli.');await update(m,r,{...JSON.parse(r.data),status},'mariage_demande_traitee');if(status==='Consentement demandé')await notice({id:r.targetOwner,tenant:m.tenant} as any,'Demande de mise en relation','L’administration vous invite à accepter ou refuser une demande dans le menu Mariage.').run();return json({message:'Suivi mis à jour.'})}
 if(b.action==='request_consent'){await requireEligible(m);const r=await record(m.tenant,String(b.id));if(!r||r.kind!=='marriage-interest'||r.targetOwner!==m.id||r.status!=='Consentement demandé')throw new AppError(403,'Demande indisponible.');if(b.accept){const source=(await list(m.tenant,'marriage')).find(x=>x.owner===r.owner);const target=await record(m.tenant,r.target);if(!source||!target||!await visibleMarriage(source)||!await visibleMarriage(target))throw new AppError(409,'Un dossier est retiré ou n’est plus éligible.');}await update(m,r,{...JSON.parse(r.data),status:z.boolean().parse(b.accept)?'Accord donné':'Refusée'},'mariage_accord_destinataire');return json({message:'Votre réponse a été transmise aux administrateurs.'})}
 throw new AppError(400,'Action inconnue.');
}catch(e){return failure(e)}}
