import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import {Document,Packer,Paragraph,Table,TableRow,TableCell,WidthType,TextRun,ImageRun} from 'docx';
import QRCode from 'qrcode';
const blue=rgb(.145,.294,.592),gray=rgb(.35,.4,.46);
const clean=(s:unknown)=>String(s??'').replace(/[^\x20-\x7e\xa0-\xff€’œŒ–—]/g,' ').replace(/œ/g,'oe').replace(/Œ/g,'OE');
export async function tablePdf(title:string,subtitle:string,columns:string[],rows:string[][],logo?:Uint8Array){const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page:any,y=0;function start(){page=pdf.addPage([595,842]);y=790;page.drawText(clean(title),{x:40,y,size:20,font:bold,color:blue});y-=28;for(const line of wrap(clean(subtitle),90)){page.drawText(line,{x:40,y,size:10,font:regular,color:gray});y-=15}y-=18;columns.forEach((v,i)=>page.drawText(clean(v),{x:40+i*515/columns.length,y,size:10,font:bold,color:blue}));y-=24}start();for(const row of rows){const lines=row.map(v=>wrap(clean(v),Math.floor(85/columns.length)));const h=Math.max(...lines.map(a=>a.length))*14+15;if(y-h<50)start();lines.forEach((ls,i)=>ls.forEach((l,j)=>page.drawText(l,{x:40+i*515/columns.length,y:y-j*14,size:10,font:regular})));y-=h}if(!rows.length)page.drawText('Aucune donnée.',{x:40,y,size:12,font:regular});const pages=pdf.getPages();for(let i=0;i<pages.length;i++)pages[i].drawText('JFSI · '+(i+1)+' / '+pages.length,{x:40,y:25,size:9,font:regular,color:gray});if(logo){const im=await pdf.embedJpg(logo);pages[0].drawImage(im,{x:515,y:772,width:40,height:40})}return pdf.save()}
function wrap(s:string,len:number){const out:string[]=[];for(const para of s.split('\n')){let line='';for(const w of para.split(' ')){if((line+w).length>len&&line){out.push(line);line=''}line+=(line?' ':'')+w}out.push(line)}return out}
export async function attendanceDocx(title:string,subtitle:string,rows:string[][],logo?:Uint8Array){const children:any[]=[];if(logo)children.push(new Paragraph({children:[new ImageRun({data:logo,type:'jpg',transformation:{width:60,height:60}})]}));children.push(new Paragraph({children:[new TextRun({text:title,bold:true,size:32})]}),new Paragraph(subtitle),new Table({width:{size:9500,type:WidthType.DXA},columnWidths:[2600,5200,1700],rows:[['Numéro membre','Nom et prénoms','Présence'],...rows].map((r,i)=>new TableRow({children:r.map(v=>new TableCell({children:[new Paragraph({children:[new TextRun({text:v,bold:i===0})]})]}))}))}));return Packer.toBuffer(new Document({sections:[{children}]}))}
export async function cardPdf(m:any,s:any,origin:string,logo:Uint8Array){const pdf=await PDFDocument.create();const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const im=await pdf.embedJpg(logo);const p=JSON.parse(m.profile);const front=pdf.addPage([486,306]);front.drawRectangle({x:0,y:0,width:486,height:306,color:rgb(.95,.97,1)});front.drawRectangle({x:0,y:0,width:486,height:28,color:blue});front.drawImage(im,{x:402,y:225,width:60,height:60});front.drawText('CARTE DE MEMBRE',{x:25,y:262,font:bold,size:20,color:blue});front.drawText(m.tenant==='demo'?'DÉMONSTRATION · PERSONNE FICTIVE':'Jardin des Frères et Soeurs en Islam',{x:25,y:240,font:regular,size:10,color:gray});const lines=[['Nom',m.name],['Prénoms',m.firstName],['N° membre',m.number],...(p.profession?[['Profession',p.profession]]:[]),['Résidence',[p.commune,p.district].filter(Boolean).join(', ')]];let y=209;for(const [label,value]of lines){front.drawText(label,{x:25,y,font:bold,size:11,color:gray});front.drawText(clean(value).slice(0,38),{x:120,y,font:regular,size:12,color:blue});y-=25}const qr=QRCode.create(origin+'/verification?numero='+encodeURIComponent(m.number),{errorCorrectionLevel:'M'});const size=qr.modules.size,unit=72/size;front.drawRectangle({x:388,y:37,width:86,height:86,color:rgb(1,1,1)});for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(qr.modules.get(r,c))front.drawRectangle({x:395+c*unit,y:44+(size-1-r)*unit,width:unit,height:unit,color:blue});front.drawText('ADHÉRENT JFSI',{x:25,y:9,font:bold,size:10,color:rgb(1,1,1)});const back=pdf.addPage([486,306]);back.drawRectangle({x:0,y:0,width:486,height:306,color:blue});back.drawImage(im,{x:213,y:208,width:60,height:60});let yy=177;for(const line of ['Jardin des Frères et Soeurs en Islam',s.slogan,...wrap(s.address,65),...s.contacts,'Carte personnelle. Présenter le QR pour vérification.']){back.drawText(clean(line),{x:25,y:yy,font:regular,size:11,color:rgb(1,1,1)});yy-=23}for(const page of pdf.getPages())page.scale(0.5,0.5);return pdf.save()}
