import { env } from 'cloudflare:workers';
export const config=()=>env as unknown as Record<string,string>;
export const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');
export async function digest(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),n=>n.toString(16).padStart(2,'0')).join('')}
export function same(a:string,b:string){let x=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)x|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return x===0}
export async function validTotp(secret:string,code:string){if(!/^[0-9]{6}$/.test(code)||!secret)return false;const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of secret.toUpperCase().replace(/=+$/,'')){const n=alphabet.indexOf(c);if(n<0)return false;bits+=n.toString(2).padStart(5,'0')}const raw=new Uint8Array((bits.match(/.{8}/g)||[]).map(s=>parseInt(s,2)));const key=await crypto.subtle.importKey('raw',raw,{name:'HMAC',hash:'SHA-1'},false,['sign']);for(let d=-1;d<=1;d++){const buf=new ArrayBuffer(8);new DataView(buf).setBigUint64(0,BigInt(Math.floor(Date.now()/30000)+d));const h=new Uint8Array(await crypto.subtle.sign('HMAC',key,buf));const o=h[19]&15;const n=(((h[o]&127)<<24)|(h[o+1]<<16)|(h[o+2]<<8)|h[o+3])%1000000;if(same(String(n).padStart(6,'0'),code))return true}return false}
export function guardOrigin(req:Request){const origin=req.headers.get('origin');if(origin!==new URL(req.url).origin)throw new AppError(403,'Origine de la requête non autorisée.');if(req.headers.get('sec-fetch-site')==='cross-site')throw new AppError(403,'Requête intersite refusée.')}
export class AppError extends Error{constructor(public status:number,message:string){super(message)}}
export const headersSecure={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'};
export function json(value:unknown,status=200,extra:Record<string,string>={}){return Response.json(value,{status,headers:{...headersSecure,...extra}})}
export function failure(e:unknown){if(e instanceof Error&&/UNIQUE constraint failed/.test(e.message+String(e.cause||'')))return json({error:'Cette opération a déjà été enregistrée.'},409);if(e instanceof AppError)return json({error:e.message},e.status);if(e&&typeof e==='object'&&'issues'in e)return json({error:'Vérifiez les champs du formulaire.',details:(e as {issues:unknown}).issues},400);console.error('JFSI request failed',e instanceof Error?e.name:'Unknown');return json({error:'Le service est momentanément indisponible. Vos données saisies sont conservées. Réessayez.'},503)}
