import {duesStatement,tariffFor} from '@/lib/billing';
import {seedEditorial} from '@/lib/editorial';
import {beginMfa,checkMfa} from '@/lib/mfa';
import {z} from 'zod';
import {context,requireMember,demoLogin,claimAdmin,sessionFor} from '@/lib/auth';
import {AppError,config,digest,failure,guardOrigin,json,same,validTotp} from '@/lib/security';
import {db,id,one,rows,statement,record,list,insert,update,audit,notice,settings,rate} from '@/lib/store';
import {active,can,eventInput,calendarDate,registration,roles,type Member} from '@/lib/domain';
import {issueOtp} from '@/lib/sms';
import programme from '@/lib/programme.json';
export const dynamic='force-dynamic';
const text=(x:unknown,min=1,max=10000)=>z.string().trim().min(min).max(max).parse(x);
const publicRecord=(r:any)=>{const {data,tenant,owner,...safe}=r;return safe};
export async function GET(req:Request){try{const q=new URL(req.url).searchParams;const resource=q.get('resource')||'context';
 if(resource==='verify'){const n=text(q.get('number'),5,70);const m=await one('SELECT name,firstName,number,status,suspended,joined,tenant FROM members WHERE number=?',n);if(!m)return json({valid:false});const s=await settings(m.tenant);const until=new Date(m.joined);until.setMonth(until.getMonth()+s.cardMonths);return json({valid:m.status==='adherent'&&!m.suspended&&until>new Date(),number:m.number,identity:m.firstName+' '+m.name[0]+'.',validUntil:until.toISOString().slice(0,10),demo:m.tenant==='demo'})}
 const c=await context();await seedEditorial(c.tenant);const s=await settings(c.tenant);
 if(resource==='context')return json({user:c.user?{name:c.user.displayName}:null,member:c.member?{...c.member,profile:{...JSON.parse(c.member.profile),phone:undefined},phone:undefined,identity:undefined}:null,settings:s,mfa:c.mfa,demo:c.tenant==='demo',smsReady:!!config().TWILIO_ACCOUNT_SID,scannerReady:!!config().MALWARE_SCAN_URL,mfaEnabled:c.member?!!(await record(c.tenant,'mfa:'+c.member.id))?.verified:false});
 if(resource==='programme'){const overrides=await list(c.tenant,'programme');return json(programme.map((p,i)=>({...p,id:String(i+1),...overrides.find(r=>r.activity===String(i+1))}))) }
 if(['events','content','structures','documents'].includes(resource)){const kind=resource==='events'?'event':resource==='structures'?'structure':resource==='documents'?'document':'content';const all=await list(c.tenant,kind);return json(all.filter(r=>can(c.member,'publish')&&c.mfa||(!r.hidden&&!r.deleted&&r.status!=='Brouillon'&&r.status!=='Archivé'&&(!r.publishAt||r.publishAt<=new Date().toISOString())&&(r.visibility==='public'||active(c.member)&&(r.visibility!=='staff'||['admin','accountant','cm','auditor'].includes(c.member!.role)&&c.mfa)))).map(publicRecord))}
 const {member:m}=await requireMember();
 if(resource==='birthdays'){if(!active(m))throw new AppError(403,'Anniversaires réservés aux membres vérifiés.');const now=new Date();const all=await rows("SELECT name,firstName,number,profile FROM members WHERE tenant=? AND suspended=0 AND status IN ('sympathisant','adherent')",m.tenant);return json({date:now.toISOString().slice(0,10),members:all.filter(u=>{const p=JSON.parse(u.profile);return p.day===now.getUTCDate()&&p.month===now.getUTCMonth()+1&&p.birthdayVisible!==false}).map(u=>({name:u.name,firstName:u.firstName,number:u.number}))})}
 if(resource==='dues'){if(!active(m))throw new AppError(403,'Compte vérifié requis.');return json(duesStatement(m,(await list(m.tenant,'payment')).filter(p=>p.owner===m.id),s))}
 if(resource==='payments'){if(!active(m))throw new AppError(403,'Le compte doit être vérifié.');return json((await list(m.tenant,'payment')).filter(p=>can(m,'finance-read')||p.owner===m.id))}
 if(resource==='finance'){if(m.status!=='adherent'&&!can(m,'finance-read')&&!can(m,'admin'))throw new AppError(403,'Synthèse réservée aux adhérents.');const payments=await rows("SELECT json_extract(data,'$.type') AS type, json_extract(data,'$.period') AS period, SUM(json_extract(data,'$.amount')) AS amount FROM records WHERE tenant=? AND kind='payment' AND json_extract(data,'$.status')='approved' GROUP BY type,period",m.tenant);const entries=await rows("SELECT json_extract(data,'$.type') AS type,json_extract(data,'$.category') AS category,SUM(json_extract(data,'$.amount')) AS amount FROM records WHERE tenant=? AND kind='finance' GROUP BY type,category",m.tenant);return json({payments,entries,updated:new Date().toISOString()})}
 if(resource==='members'){if(!can(m,'admin')&&!can(m,'attendance')&&!can(m,'finance-read'))throw new AppError(403,'Accès refusé.');const all=await rows('SELECT * FROM members WHERE tenant=? ORDER BY name',m.tenant);return json(all.map(p=>can(m,'admin')?{...p,identity:undefined,phone:undefined,profile:{...JSON.parse(p.profile),phone:undefined}}:{id:p.id,name:p.name,firstName:p.firstName,number:p.number,status:p.status,commune:JSON.parse(p.profile).commune}))}
 if(resource==='participations'){const attendance=(await list(m.tenant,'attendance')).filter(a=>a.member===m.id&&a.present);const events=await list(m.tenant,'event');return json(attendance.map(a=>events.find(e=>e.id===a.event)).filter(Boolean).map(publicRecord))}
 if(resource==='attendance'){if(!can(m,'attendance'))throw new AppError(403,'Accès refusé.');return json((await list(m.tenant,'attendance')).filter(a=>a.event===q.get('event')))}
 if(resource==='topics'){if(!active(m))throw new AppError(403,'Forum réservé aux membres vérifiés.');const topics=(await list(m.tenant,'topic')).filter(t=>(!t.hidden&&!t.deleted||can(m,'forum-moderate'))&&(t.visibility!=='staff'||['admin','accountant','cm','auditor'].includes(m.role)));const replies=(await list(m.tenant,'reply')).filter(r=>!r.hidden||can(m,'forum-moderate'));const users=await rows('SELECT id,name,firstName,scope FROM members WHERE tenant=?',m.tenant);return json({topics:topics.map(t=>({...t,scope:users.find(u=>u.id===t.owner)?.scope||'',replies:replies.filter(r=>r.topic===t.id).map(r=>({...r,scope:users.find(u=>u.id===r.owner)?.scope||''}))})),reactions:await list(m.tenant,'reaction'),favorites:(await list(m.tenant,'favorite')).filter(f=>f.owner===m.id)})}
 if(resource==='suggestions')return json((await list(m.tenant,'suggestion')).filter(r=>can(m,'admin')||r.owner===m.id));
 if(resource==='notifications')return json((await list(m.tenant,'notification')).filter(r=>r.owner===m.id));
 if(resource==='signals'){if(!can(m,'forum-moderate')&&!can(m,'feed-moderate'))throw new AppError(403,'Accès refusé.');return json((await list(m.tenant,'signal')).filter(r=>r.scope==='forum'?can(m,'forum-moderate'):can(m,'feed-moderate')))}
 if(resource==='audit'){if(!can(m,'audit'))throw new AppError(403,'Accès refusé.');return json(await rows('SELECT * FROM audit WHERE tenant=? ORDER BY created DESC LIMIT 300',m.tenant))}
 if(resource==='resources'){const event=await record(m.tenant,text(q.get('event')));if(!active(m)||!event||event.kind!=='event'||['Brouillon','Archivé'].includes(event.status)&&!can(m,'publish'))throw new AppError(404,'Événement introuvable.');return json((await list(m.tenant,'resource')).filter(r=>r.event===event.id&&r.scan==='clean'))}
 throw new AppError(404,'Ressource introuvable.');
 }catch(e){return failure(e)}}
export async function POST(req:Request){try{guardOrigin(req);if(Number(req.headers.get('content-length')||0)>70000)throw new AppError(413,'Requête trop volumineuse.');const raw=await req.text();if(raw.length>70000)throw new AppError(413,'Requête trop volumineuse.');let b:any;try{b=JSON.parse(raw)}catch{throw new AppError(400,'Requête invalide.')}const action=text(b.action,2,80);const c=await context();if(!c.user)throw new AppError(401,'Connectez-vous pour continuer.');await rate('write:'+c.user.userId,150,300);
 if(action==='demo_login')return json({ok:true},200,{'Set-Cookie':await demoLogin(b,req)});
 if(action==='admin_setup')return json({ok:true},200,{'Set-Cookie':await claimAdmin(b,req)});
 if(action==='logout'){const cookie=req.headers.get('cookie')?.match(/(?:^|; )jfsi_session=([^;]+)/)?.[1];if(cookie)await statement('DELETE FROM sessions WHERE id=? AND identity=?',await digest(cookie),c.user.userId).run();return json({ok:true},200,{'Set-Cookie':'jfsi_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'})}
 if(['mfa','mfa_begin','mfa_confirm'].includes(action)){if(!c.member||c.member.tenant!=='live')throw new AppError(403,'Compte réel requis.');await rate('mfa:'+c.user.userId,10,900);if(c.member.suspended)throw new AppError(403,'Compte suspendu.');if(action==='mfa_begin'){if(c.member.role!=='member'&&!c.mfa)throw new AppError(403,'Vérifiez votre second facteur existant avant cette opération.');return json(await beginMfa(c.member));}if(!await checkMfa(c.member,String(b.code||''),action==='mfa_confirm'))throw new AppError(401,'Code de sécurité incorrect.');return json({ok:true},200,{'Set-Cookie':await sessionFor(c.user.userId,c.member,true,req)})}
 if(action==='register'){if(c.member)throw new AppError(409,'Un dossier existe déjà pour ce compte.');const p=registration.parse(b.profile);if(await one('SELECT id FROM members WHERE tenant=? AND phone=?','live',p.phone))throw new AppError(409,'Ce numéro est déjà associé à un dossier.');const mid=id();const m={id:mid,tenant:'live'} as Member;await db().batch([statement('INSERT INTO members(id,tenant,identity,name,firstName,phone,role,status,scope,profile,joined,suspended) VALUES(?,?,?,?,?,?,?,?,?,?,?,0)',mid,'live',c.user.userId,p.name,p.firstName,p.phone,'member','pending','',JSON.stringify(p),new Date().toISOString()),audit(m,'inscription',mid),notice(m,'Demande reçue','Votre dossier sera examiné par l’administration.')]);return json({ok:true})}
 const {member:m}=await requireMember();const permission=(p:string)=>{if(!can(m,p))throw new AppError(403,'Votre profil ne possède pas cette autorisation.')};
 if(action==='profile'){const p=z.object({profession:z.string().trim().max(80),commune:z.string().trim().min(2).max(100),district:z.string().trim().min(2).max(100),email:z.union([z.string().email(),z.literal('')]),photoConsent:z.boolean(),birthdayVisible:z.boolean().default(true)}).parse(b.profile);await db().batch([statement('UPDATE members SET profile=? WHERE id=?',JSON.stringify({...JSON.parse(m.profile),...p}),m.id),audit(m,'profil_modifie',m.id)]);return json({ok:true})}
 if(action==='approve_member'||action==='reject_member'||action==='resend_otp'){let target:Member;if(action==='resend_otp'&&b.id===m.id){if(m.status!=='otp')throw new AppError(403,'Le dossier doit être approuvé avant un renvoi.');target=m;}else{permission('admin');target=await one('SELECT * FROM members WHERE id=? AND tenant=?',text(b.id),m.tenant)}if(!target)throw new AppError(404,'Dossier introuvable.');if(!['pending','otp'].includes(target.status))throw new AppError(409,'Le dossier n’attend plus cette validation.');if(action==='reject_member'){await db().batch([statement('UPDATE members SET status=? WHERE id=?','rejected',target.id),audit(m,'dossier_rejete',target.id,text(b.reason,3,1000)),notice(target,'Dossier rejeté',text(b.reason,3,1000))]);return json({ok:true})}return json(await issueOtp(m,target))}
 if(action==='verify_otp'){if(m.status!=='otp')throw new AppError(409,'Aucune vérification en attente.');await rate('verify:'+m.id,10,600);const code=z.string().regex(/^\d{7}$/).parse(b.code);const otp=await one('SELECT * FROM otps WHERE member=?',m.id);if(!otp||otp.expires<Date.now()||otp.attempts>=5)throw new AppError(400,'Code expiré ou trop de tentatives. Demandez un nouveau code.');await statement('UPDATE otps SET attempts=attempts+1 WHERE member=?',m.id).run();if(!same(otp.hash,await digest(code+':'+m.id)))throw new AppError(400,'Code incorrect.');const result=await db().batch([statement("UPDATE members SET status='sympathisant' WHERE id=? AND status='otp' AND EXISTS(SELECT 1 FROM otps WHERE member=? AND hash=? AND expires>? AND attempts<=5)",m.id,m.id,otp.hash,Date.now()),statement('DELETE FROM otps WHERE member=?',m.id),audit(m,'otp_valide',m.id),notice(m,'Bienvenue au JFSI','Votre compte sympathisant est activé.')]);if(!result[0].meta.changes)throw new AppError(409,'Code déjà utilisé.');return json({ok:true})}
 if(action==='payment'){permission('member');const s=await settings(m.tenant);const data=z.object({type:z.enum(['adhesion','cotisation','don']),period:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),amount:z.coerce.number().int().positive().max(100000000),operator:z.enum(['Orange Money','Wave','MTN Money']),reference:z.string().max(100),date:z.string().min(10).max(40),proof:z.string().min(10)}).parse(b);if(data.type==='adhesion'&&m.status==='adherent')throw new AppError(409,'Votre adhésion est déjà validée.');if(data.type==='cotisation'&&m.status!=='adherent')throw new AppError(403,'Cotisation réservée aux adhérents.');if(data.type==='cotisation'){const horizon=new Date();horizon.setUTCFullYear(horizon.getUTCFullYear()+5);if(data.period<m.joined.slice(0,7)||data.period>horizon.toISOString().slice(0,7))throw new AppError(400,'Choisissez un mois depuis votre adhésion et au maximum cinq ans à l’avance.')}if(data.type==='adhesion'&&data.amount!==s.adhesion||data.type==='cotisation'&&data.amount!==tariffFor(data.period,s))throw new AppError(400,'Le montant ne correspond pas au tarif en vigueur.');const file=await record(m.tenant,data.proof);if(!file||file.owner!==m.id||file.kind!=='file'||file.purpose!=='proof')throw new AppError(403,'Preuve de paiement non autorisée.');const existing=(await list(m.tenant,'payment')).find(p=>p.owner===m.id&&p.type===data.type&&p.period===data.period&&p.status!=='rejected');if(data.type!=='don'&&existing)throw new AppError(409,'Un paiement existe déjà pour cette période.');const pid=id();await db().batch([insert(m.tenant,'payment',m.id,{...data,status:'submitted',memberName:m.firstName+' '+m.name},pid),audit(m,'preuve_deposee',pid)]);return json({ok:true,id:pid})}
 if(action==='review_payment'){permission('finance');const p=await record(m.tenant,text(b.id));if(!p||p.kind!=='payment')throw new AppError(404,'Paiement introuvable.');if(p.owner===m.id)throw new AppError(403,'Vous ne pouvez pas valider votre propre paiement.');if(p.status!=='submitted')throw new AppError(409,'Ce paiement a déjà été traité.');const accept=z.boolean().parse(b.accept);const reason=accept?'':text(b.reason,3,1000);const proof=await record(m.tenant,p.proof);if(accept&&proof?.scan!=='clean')throw new AppError(409,'L’analyse de sécurité de la preuve doit être terminée.');const member=await one('SELECT * FROM members WHERE id=? AND tenant=?',p.owner,m.tenant);if(!member||!active(member))throw new AppError(409,'Membre non actif.');const paidAt=new Date().toISOString();const number=member.number||'JFSI-'+paidAt.slice(0,4)+'-'+id().slice(0,8).toUpperCase();const claim='payment:'+p.id;const data={...JSON.parse(p.data),status:accept?'approved':'rejected',reason,approvedAt:paidAt,reviewer:m.id,receipt:accept?'REC-'+id().slice(0,12).toUpperCase():null};const ops=[statement('INSERT INTO claims(id,value) VALUES(?,?)',claim,m.id),statement('UPDATE records SET data=?,obligation=?,version=version+1,updated=? WHERE id=? AND version=?',JSON.stringify(data),accept?p.obligation:null,paidAt,p.id,p.version),audit(m,accept?'paiement_valide':'paiement_rejete',p.id,reason),notice(member,accept?'Paiement validé':'Paiement rejeté',accept?'Votre reçu est disponible.':reason)];if(accept&&p.type==='adhesion')ops.push(statement("UPDATE members SET status='adherent',number=?,joined=? WHERE id=? AND tenant=?",number,paidAt,p.owner,m.tenant));await db().batch(ops);return json({ok:true})}
 if(action==='event'){permission('publish');const data=eventInput.parse(b.event);if(b.id){const r=await record(m.tenant,text(b.id));if(!r||r.kind!=='event')throw new AppError(404,'Événement introuvable.');await update(m,r,data,'evenement_modifie')}else{const key=id();await db().batch([insert(m.tenant,'event',m.id,data,key),audit(m,'evenement_cree',key)])}return json({ok:true})}
 if(action==='attendance'){permission('attendance');const e=await record(m.tenant,text(b.event));if(!e||e.kind!=='event')throw new AppError(404,'Événement introuvable.');if(new Date(e.date+'T'+e.time+':00Z')>new Date())throw new AppError(400,'Les présences sont saisies après l’événement.');const member=await one('SELECT id FROM members WHERE tenant=? AND id=?',m.tenant,text(b.member));if(!member)throw new AppError(404,'Membre introuvable.');const present=z.boolean().parse(b.present),reason=text(b.reason,3,500);const key='attendance:'+e.id+':'+member.id;const data=JSON.stringify({event:e.id,member:member.id,present,reason});await db().batch([statement('INSERT INTO records(id,tenant,kind,owner,data,version,updated) VALUES(?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,version=version+1,updated=excluded.updated',key,m.tenant,'attendance',member.id,data,new Date().toISOString()),audit(m,'presence_modifiee',key,reason)]);return json({ok:true})}
 if(action==='topic'||action==='reply'){permission('member');const body=text(b.body,3,5000);const title=action==='topic'?text(b.title,3,150):'';if(b.charter!==true)throw new AppError(400,'Acceptez la charte du forum.');if(action==='reply'){const parent=await record(m.tenant,text(b.topic));if(!parent||parent.kind!=='topic'||parent.hidden||parent.locked)throw new AppError(403,'Cette discussion est indisponible ou verrouillée.')}const key=id();await db().batch([insert(m.tenant,action,m.id,{title,body,topic:b.topic||'',category:String(b.category||'Discussion libre').slice(0,80),hidden:false,locked:false,author:m.firstName+' '+m.name},key),audit(m,action+'_cree',key)]);return json({ok:true})}
 if(action==='moderate'){const r=await record(m.tenant,text(b.id));if(!r||!['topic','reply','content'].includes(r.kind))throw new AppError(404,'Contenu introuvable.');permission(r.kind==='content'?'feed-moderate':'forum-moderate');const reason=text(b.reason,3,1000);const mode=z.enum(['hide','restore','lock','unlock','delete']).parse(b.mode);await update(m,r,{...JSON.parse(r.data),hidden:mode==='hide'||mode==='delete'?true:mode==='restore'?false:r.hidden||false,locked:mode==='lock'?true:mode==='unlock'?false:r.locked||false,deleted:mode==='delete'||r.deleted||false},'moderation_'+mode,reason);return json({ok:true})}
 if(action==='signal'){permission('member');const target=await record(m.tenant,text(b.target));if(!target||!['topic','reply','content'].includes(target.kind))throw new AppError(404,'Contenu introuvable.');await insert(m.tenant,'signal',m.id,{target:target.id,scope:target.kind==='content'?'feed':'forum',reason:text(b.reason,3,1000),status:'Reçu'}).run();return json({ok:true})}
 if(action==='reaction'||action==='favorite'){permission('member');const target=await record(m.tenant,text(b.target));if(!target||!['topic','reply','content'].includes(target.kind)||target.hidden)throw new AppError(404,'Contenu introuvable.');const key=action+':'+m.id+':'+target.id;const old=await record(m.tenant,key);if(old)await statement('DELETE FROM records WHERE id=? AND owner=?',key,m.id).run();else await insert(m.tenant,action,m.id,{target:target.id},key).run();return json({ok:true})}
 if(action==='suggestion'){permission('member');const key=id();await insert(m.tenant,'suggestion',m.id,{category:text(b.category,2,50),body:text(b.body,5,5000),status:'Reçu',response:'',tracking:'JFSI-'+key.slice(0,8).toUpperCase()},key).run();return json({ok:true,id:key})}
 if(action==='suggestion_reply'){permission('admin');const r=await record(m.tenant,text(b.id));if(!r||r.kind!=='suggestion')throw new AppError(404,'Suggestion introuvable.');await update(m,r,{...JSON.parse(r.data),response:text(b.response,3,5000),status:z.enum(['En étude','Transmis','Répondu','Clôturé']).parse(b.status)},'suggestion_repondue');return json({ok:true})}
 if(action==='roles'){permission('admin');const member=await one('SELECT * FROM members WHERE id=? AND tenant=?',text(b.id),m.tenant);if(!member)throw new AppError(404,'Membre introuvable.');if(member.id===m.id)throw new AppError(403,'Vous ne pouvez pas modifier vos propres habilitations.');const role=z.enum(roles).parse(b.role),scope=z.enum(['','forum','feed','both']).parse(b.scope);if(m.tenant==='live'&&role!=='member'&&!(await record(m.tenant,'mfa:'+member.id))?.verified)throw new AppError(409,'Ce membre doit d’abord activer son authentification à deux facteurs dans Mon profil.');await db().batch([statement('UPDATE members SET role=?,scope=?,suspended=? WHERE id=?',role,scope,z.boolean().parse(b.suspended)?1:0,member.id),statement('DELETE FROM sessions WHERE member=?',member.id),audit(m,'habilitations_modifiees',member.id,text(b.reason,3,1000))]);return json({ok:true})}
 if(action==='settings'){permission('admin');const s=z.object({adhesion:z.coerce.number().int().min(1).max(1000000),monthly:z.coerce.number().int().min(1).max(1000000),contacts:z.array(z.string().regex(/^\+[1-9]\d{7,14}$/)).length(2),orange:z.string().regex(/^\+[1-9]\d{7,14}$/),wave:z.string().regex(/^\+[1-9]\d{7,14}$/),mtn:z.string().regex(/^\+[1-9]\d{7,14}$/),address:z.string().min(5).max(300),facebook:z.union([z.string().url().startsWith('https://'),z.literal('')]),year:z.coerce.number().int().min(2020).max(2100),cardMonths:z.coerce.number().int().min(1).max(120),otpMinutes:z.coerce.number().int().min(1).max(10),otpAttempts:z.literal(5),otpResends:z.literal(3),uploadMB:z.coerce.number().int().min(1).max(5),slogan:z.string().max(200)}).parse(b.settings);const old=await settings(m.tenant);const effective=new Date();effective.setUTCDate(1);effective.setUTCMonth(effective.getUTCMonth()+1);const from=effective.toISOString().slice(0,7);const duesRates=[...(old.duesRates||[{from:'0000-01',amount:old.monthly}]).filter((r:any)=>r.from!==from),{from,amount:s.monthly}];await db().batch([statement('INSERT INTO settings(tenant,data,version) VALUES(?,?,1) ON CONFLICT(tenant) DO UPDATE SET data=excluded.data,version=version+1',m.tenant,JSON.stringify({...s,duesRates})),audit(m,'parametres_modifies',m.tenant,text(b.reason,3,1000))]);return json({ok:true})}
 if(action==='content'||action==='structure'){permission(action==='structure'?'admin':'publish');const data=z.object({title:z.string().trim().min(3).max(150),body:z.string().trim().min(10).max(15000),category:z.string().max(80),visibility:z.enum(['public','members','staff']),status:z.enum(['Brouillon','Publié','Archivé']),publishAt:z.string().max(30).default(''),sortDate:z.union([calendarDate,z.literal('')]).default(''),dateLabel:z.string().max(100).default('')}).parse(b.content);if(data.category==='Membre à l’honneur'&&b.consent!==true)throw new AppError(400,'Le consentement de la personne est requis.');if(b.id){const old=await record(m.tenant,text(b.id));if(!old||old.kind!==action)throw new AppError(404,'Publication introuvable.');await update(m,old,{...JSON.parse(old.data),...data,consent:!!b.consent,eventMonth:data.sortDate?Number(data.sortDate.slice(5,7)):old.eventMonth},action+'_modifie')}else{const key=id();await db().batch([insert(m.tenant,action,m.id,{...data,consent:!!b.consent},key),audit(m,action+'_cree',key)])}return json({ok:true})}
 if(action==='finance_entry'){permission('finance');const data=z.object({title:z.string().min(3).max(150),category:z.string().min(2).max(80),amount:z.coerce.number().int().positive().max(100000000),type:z.enum(['recette','depense']),date:calendarDate}).parse(b.entry);const key=id();await db().batch([insert(m.tenant,'finance',m.id,data,key),audit(m,'ecriture_financiere',key)]);return json({ok:true})}
 if(action==='volunteer'){permission('member');const activity=text(b.activity,1,10);if(!programme[Number(activity)-1])throw new AppError(404,'Activité introuvable.');const key='volunteer:'+m.id+':'+activity;await statement('INSERT OR IGNORE INTO records(id,tenant,kind,owner,data,version,updated) VALUES(?,?,?,?,?,1,?)',key,m.tenant,'volunteer',m.id,JSON.stringify({activity}),new Date().toISOString()).run();return json({ok:true})}
 if(action==='programme'){permission('admin');const activity=text(b.activity,1,10);if(!programme[Number(activity)-1])throw new AppError(404,'Activité introuvable.');const status=z.enum(['À planifier','Planifiée','En préparation','En cours','Terminée','Reportée','Annulée']).parse(b.status);const key='programme:'+m.tenant+':'+activity;await db().batch([statement('INSERT INTO records(id,tenant,kind,owner,data,version,updated) VALUES(?,?,?,?,?,1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,version=version+1,updated=excluded.updated',key,m.tenant,'programme',m.id,JSON.stringify({activity,status}),new Date().toISOString()),audit(m,'programme_modifie',key)]);return json({ok:true})}
 if(action==='notification_read'){const r=await record(m.tenant,text(b.id));if(!r||r.kind!=='notification'||r.owner!==m.id)throw new AppError(404,'Notification introuvable.');await update(m,r,{...JSON.parse(r.data),read:true},'notification_lue');return json({ok:true})}
 throw new AppError(404,'Action inconnue.');
 }catch(e){return failure(e)}}
